version: "3.3"
services:
  retail:
    image: khancock/simple-app
    ports:
      - "8080:8080"
    links:
      - mongo
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == vm0
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == aws01